#!/usr/bin/env python3
"""Render a single review sheet showing every generated asset, per brand.

    python3 tools/og/contact-sheet.py [out.png]

Not a site asset — this is a proof sheet for eyeballing a rebuild. Defaults to
writing outside the repo so it never ships.
"""
import json
import sys
from pathlib import Path

from playwright.sync_api import sync_playwright

sys.path.insert(0, str(Path(__file__).parent))
import templates as T  # noqa: E402

ROOT = Path(__file__).resolve().parents[2]
CFG = json.loads((Path(__file__).parent / "brand.json").read_text())

SOCIAL = [("og.png", "og:image  1200×630"), ("og-square.jpg", "square  1200×1200"),
          ("og-portrait.jpg", "portrait  1080×1350"), ("og-story.jpg", "story  1080×1920"),
          ("x-header.jpg", "X header  1500×500"),
          ("linkedin-banner.jpg", "LinkedIn  1584×396"),
          ("youtube-banner.jpg", "YouTube  2560×1440"), ("avatar.png", "avatar  1024²")]
LOGOS = [("logo.png", "logo.png  1200×400"), ("logo-square.png", "logo-square.png  512²")]
ICONS = [("favicon-32.png", "32"), ("favicon-48.png", "48"), ("mstile-150.png", "150"),
         ("icon-192.png", "192"), ("icon-512.png", "512"),
         ("icon-maskable-512.png", "maskable")]


def sections():
    out = []
    for site in CFG["sites"]:
        root = ROOT / site["root"]
        soc = root / site["assetBase"] / "social"
        ico = root / site["assetBase"] / "icons"
        c1, c2 = site["accent"]

        logos = "".join(
            f'<figure><img src="{(root / site["assetBase"] / f).as_uri()}"><figcaption>{cap}</figcaption></figure>'
            for f, cap in LOGOS if (root / site["assetBase"] / f).exists())
        tiles = "".join(
            f'<figure><img src="{(soc / f).as_uri()}" loading="eager"><figcaption>{cap}</figcaption></figure>'
            for f, cap in SOCIAL if (soc / f).exists())
        pages = "".join(
            f'<figure class="sm"><img src="{(soc / p).as_uri()}"><figcaption>{p}</figcaption></figure>'
            for p in sorted(x.name for x in soc.glob("og-*.png")))
        icons = "".join(
            f'<figure class="ico"><img src="{(ico / f).as_uri()}"><figcaption>{cap}</figcaption></figure>'
            for f, cap in ICONS if (ico / f).exists())
        icons += (f'<figure class="ico"><img src="{(root / "apple-touch-icon.png").as_uri()}">'
                  f'<figcaption>apple 180</figcaption></figure>')

        out.append(f"""<section>
  <header><span class="swatch" style="background:linear-gradient(120deg,{c1},{c2})"></span>
    <h2>{site['name']}</h2><code>{site['domain']}</code>
    <span class="hex">{c1} → {c2}</span></header>
  <div class="grid">{tiles}</div>
  <h3>Logo lockups</h3><div class="grid">{logos}</div>
  <h3>Per-page share cards</h3><div class="grid">{pages}</div>
  <h3>Icons</h3><div class="grid icons">{icons}</div>
</section>""")
    return "".join(out)


HTML = f"""<!doctype html><meta charset="utf-8"><style>
{T.font_css()}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{background:#06070B;color:#EEF0F6;font-family:Inter,sans-serif;padding:56px;width:1760px}}
h1{{font-family:"Space Grotesk",sans-serif;font-size:34px;letter-spacing:-.02em;margin-bottom:6px}}
.lede{{color:#98A1B2;font-size:15px;margin-bottom:44px}}
section{{margin-bottom:56px;padding-bottom:44px;border-bottom:1px solid rgba(255,255,255,.09)}}
section header{{display:flex;align-items:center;gap:14px;margin-bottom:22px}}
.swatch{{width:26px;height:26px;border-radius:8px}}
h2{{font-family:"Space Grotesk",sans-serif;font-size:23px;letter-spacing:-.02em}}
code,.hex{{font-family:"JetBrains Mono",monospace;font-size:12.5px;color:#7C8698}}
.hex{{margin-left:auto}}
h3{{font-size:12px;text-transform:uppercase;letter-spacing:.15em;color:#646D7E;
   margin:28px 0 14px;font-weight:600}}
.grid{{display:flex;flex-wrap:wrap;gap:18px;align-items:flex-start}}
figure{{width:400px}}
figure.sm{{width:258px}}
figure.ico{{width:auto}}
img{{width:100%;display:block;border-radius:8px;border:1px solid rgba(255,255,255,.11);
   background:#0A0C12}}
.ico img{{width:auto;height:76px;border-radius:14px}}
figcaption{{font-family:"JetBrains Mono",monospace;font-size:10.5px;color:#7C8698;
   margin-top:7px;text-align:center}}
</style>
<h1>GetApps — social &amp; icon assets</h1>
<p class="lede">Generated by <code>tools/og/generate.py</code> from <code>tools/og/brand.json</code>.</p>
{sections()}"""


def main():
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else Path("/tmp/getapps-social-sheet.png")
    with sync_playwright() as pw:
        b = pw.chromium.launch()
        pg = b.new_context(device_scale_factor=1).new_page()
        pg.set_viewport_size({"width": 1760, "height": 1400})
        # Written to a real file rather than set_content: an about:blank
        # document cannot pull file:// images.
        tmp = out.with_suffix(".html")
        tmp.write_text(HTML)
        pg.goto(tmp.as_uri(), wait_until="load")
        pg.evaluate("""async () => {
            await document.fonts.ready;
            await Promise.all([...document.images]
                .filter(i => !i.complete)
                .map(i => new Promise(r => { i.onload = i.onerror = r; })));
        }""")
        broken = pg.evaluate(
            "[...document.images].filter(i => !i.naturalWidth).map(i => i.src)")
        if broken:
            raise SystemExit(f"{len(broken)} image(s) failed to load, e.g. {broken[0]}")
        pg.screenshot(path=str(out), full_page=True)
        tmp.unlink()
        b.close()
    print(f"{out}  {out.stat().st_size / 1024 / 1024:.1f} MB")


if __name__ == "__main__":
    main()
