#!/usr/bin/env python3
"""Write the social + icon <head> tags into every page listed in brand.json.

Idempotent: the tags live inside a marked region, so re-running replaces the
region rather than duplicating it. Run after tools/og/generate.py.

    python3 tools/og/inject-meta.py            # all sites
    python3 tools/og/inject-meta.py getjson    # one site
    python3 tools/og/inject-meta.py --check    # exit 1 if any page is stale
"""

import html
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
CFG = json.loads((Path(__file__).parent / "brand.json").read_text())

BEGIN = "<!-- social:begin — generated by tools/og/inject-meta.py, do not edit -->"
END = "<!-- social:end -->"
REGION = re.compile(re.escape(BEGIN) + r".*?" + re.escape(END), re.S)

# Anchor: the last existing twitter: meta on the page. Falls back to </head>.
LAST_TWITTER = re.compile(r'^[ \t]*<meta name="twitter:[^>]*>[ \t]*$', re.M)

# The hand-written SVG favicon link is absorbed into the block so that the
# SVG always precedes the PNG fallbacks, whatever order the page had it in.
SVG_ICON = re.compile(r'^[ \t]*<link rel="icon"[^>]*favicon\.svg[^>]*>[ \t]*\n', re.M)

LD_JSON = re.compile(r'<script[^>]*type="application/ld\+json"[^>]*>(.*?)</script>', re.S)


def has_top_level_org(src):
    """True when the page already declares an Organization as its own entity.

    Deliberately not a substring match: most product pages nest an
    Organization under an article's `publisher`, which is not the same thing
    and carries no logo — those pages still need a node of their own.
    """
    for raw in LD_JSON.findall(src):
        try:
            data = json.loads(raw)
        except json.JSONDecodeError:
            continue
        nodes = data if isinstance(data, list) else [data]
        for node in list(nodes):
            if isinstance(node, dict) and isinstance(node.get("@graph"), list):
                nodes.extend(node["@graph"])
        if any(isinstance(n, dict) and n.get("@type") == "Organization" for n in nodes):
            return True
    return False


def org_jsonld(site, img):
    """Compact Organization node carrying the logo Google reads for search."""
    origin = site["origin"]
    ub = site["urlBase"]
    return json.dumps({
        "@context": "https://schema.org",
        "@type": "Organization",
        "@id": f"{origin}/#organization",
        "name": site["name"],
        "url": f"{origin}/",
        "description": site["manifest"]["description"],
        "logo": {
            "@type": "ImageObject",
            "url": f"{origin}{ub}/logo-square.png",
            "width": 512,
            "height": 512,
        },
        "image": img,
    }, indent=2)


def block(site, page, has_org=False):
    origin = site["origin"]
    ub = site["urlBase"]
    # Archived copies point at the landing card they canonicalise to.
    stem = "og" if page.get("primary") or page.get("reuse") else f"og-{page['key']}"
    img = f"{origin}{ub}/social/{stem}.png"
    headline = page.get("headline") or site["manifest"]["description"]
    alt = html.escape(f"{headline.replace(chr(10), ' ')} — {site['name']}", quote=True)
    name = html.escape(site["name"], quote=True)
    accent = site["accent"][0]
    logo = f"{origin}{ub}/logo.png"

    lines = [
        BEGIN,
        f'<meta property="og:image" content="{img}">',
        f'<meta property="og:image:secure_url" content="{img}">',
        '<meta property="og:image:type" content="image/png">',
        '<meta property="og:image:width" content="1200">',
        '<meta property="og:image:height" content="630">',
        f'<meta property="og:image:alt" content="{alt}">',
        f'<meta name="twitter:image" content="{img}">',
        f'<meta name="twitter:image:alt" content="{alt}">',
        f'<meta property="og:logo" content="{logo}">',
        f'<link rel="image_src" href="{img}">',
        "",
        f'<link rel="icon" href="{ub}/favicon.svg" type="image/svg+xml">',
        f'<link rel="icon" href="{ub}/icons/favicon-32.png" sizes="32x32" type="image/png">',
        f'<link rel="icon" href="{ub}/icons/favicon-16.png" sizes="16x16" type="image/png">',
        '<link rel="apple-touch-icon" sizes="180x180" href="/apple-touch-icon.png">',
        f'<link rel="mask-icon" href="{ub}/icons/safari-pinned-tab.svg" color="{accent}">',
        '<link rel="manifest" href="/site.webmanifest">',
        f'<meta name="application-name" content="{name}">',
        f'<meta name="apple-mobile-web-app-title" content="{name}">',
        '<meta name="msapplication-TileColor" content="#06070B">',
        '<meta name="msapplication-config" content="/browserconfig.xml">',
    ]
    if not has_org:
        lines += ["", '<script type="application/ld+json">',
                  org_jsonld(site, img), "</script>"]
    return "\n".join(lines + [END])


PLACEHOLDER = "\x00social-region\x00"


def apply(path: Path, new_block: str) -> str:
    """Return the page source with the social region inserted or refreshed."""
    src = path.read_text()

    # Park an existing region, then strip any hand-written SVG favicon link
    # from the rest of the page — the block owns it now, and it has to sit
    # ahead of the PNG fallbacks for browsers that pick the first match.
    had_region = bool(REGION.search(src))
    if had_region:
        src = REGION.sub(PLACEHOLDER, src, count=1)
    src = SVG_ICON.sub("", src)

    if had_region:
        return src.replace(PLACEHOLDER, new_block, 1)

    anchors = list(LAST_TWITTER.finditer(src))
    if anchors:
        at = anchors[-1].end()
        return src[:at] + "\n\n" + new_block + src[at:]
    if "</head>" in src:
        return src.replace("</head>", new_block + "\n</head>", 1)
    raise SystemExit(f"{path}: no twitter meta and no </head> to anchor to")


def main():
    args = sys.argv[1:]
    check = "--check" in args
    only = [a for a in args if not a.startswith("--")] or None

    changed, stale = 0, []
    for site in CFG["sites"]:
        if only and site["key"] not in only:
            continue
        for page in site["pages"]:
            path = ROOT / site["root"] / page["file"]
            if not path.exists():
                print(f"  ! missing {path}", file=sys.stderr)
                continue
            src = path.read_text()
            outside = REGION.sub("", src)
            out = apply(path, block(site, page, has_org=has_top_level_org(outside)))
            rel = path.relative_to(ROOT)
            if out == path.read_text():
                print(f"  = {rel}")
                continue
            stale.append(str(rel))
            if not check:
                path.write_text(out)
                changed += 1
                print(f"  ✓ {rel}")

    if check:
        if stale:
            print(f"\n{len(stale)} page(s) out of date: " + ", ".join(stale))
            sys.exit(1)
        print("\nAll pages up to date.")
    else:
        print(f"\n✓ {changed} page(s) updated")


if __name__ == "__main__":
    main()
